### ISSUE TITLE
PlugConnWrapperError

### ISSUE THREAD

**Issue by schurig** [schurig/aws-ses-log#5]
**Message**

```
  HTTP request error: ** (FunctionClauseError) no function clause matching in SesLog.Bounce.json_object/1
```

**Backtrace (last 10 lines)**

```
(ses_log) web/models/bounce.ex:76: SesLog.Bounce.json_object(%SesLog.Bounce{__meta__: #Ecto.Schema.Metadata<:loaded, "bounces">, bounced_recipients: ["hr-info@project-a.com"], email: #Ecto.Association.NotLoaded<association :email is not loaded>, email_id: 111, feedback_id: "01020157dd9f1cfe-2ad07bec-9613-11e6-9da5-d5a049580e95-000000", id: 25, inserted_at: %DateTime{calendar: Calendar.ISO, day: 19, hour: 15, microsecond: {570335, 6}, minute: 46, month: 10, second: 15, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2016, zone_abbr: "UTC"}, sub_type: "Undetermined", subscription: #Ecto.Association.NotLoaded<association :subscription is not loaded>, subscription_id: 9, timestamp: %DateTime{calendar: Calendar.ISO, day: 19, hour: 15, microsecond: {0, 6}, minute: 46, month: 10, second: 9, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2016, zone_abbr: "UTC"}, topic: #Ecto.Association.NotLoaded<association :topic is not loaded>, topic_id: 7, type: "Undetermined", updated_at: %DateTime{calendar: Calendar.ISO, day: 19, hour: 15, microsecond: {570341, 6}, minute: 46, month: 10, second: 15, std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2016, zone_abbr: "UTC"}})
(ses_log) web/views/log_view.ex:90: SesLog.LogView.pretty_json/1
(ses_log) web/templates/log/index.html.eex:60: anonymous fn/3 in SesLog.LogView.index.html/1
(elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
(ses_log) web/templates/log/index.html.eex:40: SesLog.LogView."index.html"/1
(ses_log) web/templates/layout/app.html.eex:36: SesLog.LayoutView."app.html"/1
(phoenix) lib/phoenix/view.ex:335: Phoenix.View.render_to_iodata/3
(ses_log) lib/ses_log/endpoint.ex:1: SesLog.Endpoint.instrument/4
```

View on AppSignal: https://appsignal.com/symetics/sites/57f63fd46a21db56ab04f1cf/web/exceptions/PlugConnWrapperError

**Comment by schurig** [comment]
fixed with 2b8e05d
